#
# Generated by erpcgen 1.10.0 on Sat Apr 22 14:59:30 2023.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for rpc_wifi_drv
class Irpc_wifi_drv(object):
    SERVICE_ID = 14
    RPC_WIFI_CONNECT_ID = 1
    RPC_WIFI_CONNECT_BSSID_ID = 2
    RPC_WIFI_DISCONNECT_ID = 3
    RPC_WIFI_IS_CONNECTED_TO_AP_ID = 4
    RPC_WIFI_IS_UP_ID = 5
    RPC_WIFI_IS_READY_TO_TRANSCEIVE_ID = 6
    RPC_WIFI_SET_MAC_ADDRESS_ID = 7
    RPC_WIFI_GET_MAC_ADDRESS_ID = 8
    RPC_WIFI_ENABLE_POWERSAVE_ID = 9
    RPC_WIFI_RESUME_POWERSAVE_ID = 10
    RPC_WIFI_DISABLE_POWERSAVE_ID = 11
    RPC_WIFI_BTCOEX_SET_BT_ON_ID = 12
    RPC_WIFI_BTCOEX_SET_BT_OFF_ID = 13
    RPC_WIFI_GET_ASSOCIATED_CLIENT_LIST_ID = 14
    RPC_WIFI_GET_AP_BSSID_ID = 15
    RPC_WIFI_GET_AP_INFO_ID = 16
    RPC_WIFI_SET_COUNTRY_ID = 17
    RPC_WIFI_GET_STA_MAX_DATA_RATE_ID = 18
    RPC_WIFI_GET_RSSI_ID = 19
    RPC_WIFI_SET_CHANNEL_ID = 20
    RPC_WIFI_GET_CHANNEL_ID = 21
    RPC_WIFI_CHANGE_CHANNEL_PLAN_ID = 22
    RPC_WIFI_REGISTER_MULTICAST_ADDRESS_ID = 23
    RPC_WIFI_UNREGISTER_MULTICAST_ADDRESS_ID = 24
    RPC_WIFI_RF_ON_ID = 25
    RPC_WIFI_RF_OFF_ID = 26
    RPC_WIFI_ON_ID = 27
    RPC_WIFI_OFF_ID = 28
    RPC_WIFI_SET_MODE_ID = 29
    RPC_WIFI_OFF_FASTLY_ID = 30
    RPC_WIFI_SET_POWER_MODE_ID = 31
    RPC_WIFI_SET_TDMA_PARAM_ID = 32
    RPC_WIFI_SET_LPS_DTIM_ID = 33
    RPC_WIFI_GET_LPS_DTIM_ID = 34
    RPC_WIFI_SET_LPS_THRESH_ID = 35
    RPC_WIFI_SET_LPS_LEVEL_ID = 36
    RPC_WIFI_SET_MFP_SUPPORT_ID = 37
    RPC_WIFI_START_AP_ID = 38
    RPC_WIFI_START_AP_WITH_HIDDEN_SSID_ID = 39
    RPC_WIFI_SET_PSCAN_CHAN_ID = 40
    RPC_WIFI_GET_SETTING_ID = 41
    RPC_WIFI_SET_NETWORK_MODE_ID = 42
    RPC_WIFI_GET_NETWORK_MODE_ID = 43
    RPC_WIFI_SET_WPS_PHASE_ID = 44
    RPC_WIFI_RESTART_AP_ID = 45
    RPC_WIFI_CONFIG_AUTORECONNECT_ID = 46
    RPC_WIFI_SET_AUTORECONNECT_ID = 47
    RPC_WIFI_GET_AUTORECONNECT_ID = 48
    RPC_WIFI_GET_LAST_ERROR_ID = 49
    RPC_WIFI_ADD_CUSTOM_IE_ID = 50
    RPC_WIFI_UPDATE_CUSTOM_IE_ID = 51
    RPC_WIFI_DEL_CUSTOM_IE_ID = 52
    RPC_WIFI_SET_INDICATE_MGNT_ID = 53
    RPC_WIFI_GET_DRV_ABILITY_ID = 54
    RPC_WIFI_SET_CHANNEL_PLAN_ID = 55
    RPC_WIFI_GET_CHANNEL_PLAN_ID = 56
    RPC_WIFI_ENABLE_FORWARDING_ID = 57
    RPC_WIFI_DISABLE_FORWARDING_ID = 58
    RPC_WIFI_SET_CH_DEAUTH_ID = 59
    RPC_WIFI_GET_BAND_TYPE_ID = 60
    RPC_WIFI_SET_TX_PAUSE_DATA_ID = 61
    RPC_WIFI_GET_RECONNECT_DATA_ID = 62
    RPC_WIFI_CLEAR_RECONNECT_DATA_ID = 63
    RPC_WIFI_SCAN_START_ID = 64
    RPC_WIFI_IS_SCANING_ID = 65
    RPC_WIFI_SCAN_GET_AP_RECORDS_ID = 66
    RPC_WIFI_SCAN_GET_AP_NUM_ID = 67

    def rpc_wifi_connect(self, ssid, password, security_type, key_id, semaphore):
        raise NotImplementedError()

    def rpc_wifi_connect_bssid(self, bssid, ssid, password, security_type, key_id, semaphore):
        raise NotImplementedError()

    def rpc_wifi_disconnect(self):
        raise NotImplementedError()

    def rpc_wifi_is_connected_to_ap(self):
        raise NotImplementedError()

    def rpc_wifi_is_up(self, itf):
        raise NotImplementedError()

    def rpc_wifi_is_ready_to_transceive(self, itf):
        raise NotImplementedError()

    def rpc_wifi_set_mac_address(self, mac):
        raise NotImplementedError()

    def rpc_wifi_get_mac_address(self, mac):
        raise NotImplementedError()

    def rpc_wifi_enable_powersave(self):
        raise NotImplementedError()

    def rpc_wifi_resume_powersave(self):
        raise NotImplementedError()

    def rpc_wifi_disable_powersave(self):
        raise NotImplementedError()

    def rpc_wifi_btcoex_set_bt_on(self):
        raise NotImplementedError()

    def rpc_wifi_btcoex_set_bt_off(self):
        raise NotImplementedError()

    def rpc_wifi_get_associated_client_list(self, client_list_buffer, buffer_length):
        raise NotImplementedError()

    def rpc_wifi_get_ap_bssid(self, bssid):
        raise NotImplementedError()

    def rpc_wifi_get_ap_info(self, ap_info, security):
        raise NotImplementedError()

    def rpc_wifi_set_country(self, country_code):
        raise NotImplementedError()

    def rpc_wifi_get_sta_max_data_rate(self, inidata_rate):
        raise NotImplementedError()

    def rpc_wifi_get_rssi(self, pRSSI):
        raise NotImplementedError()

    def rpc_wifi_set_channel(self, channel):
        raise NotImplementedError()

    def rpc_wifi_get_channel(self, channel):
        raise NotImplementedError()

    def rpc_wifi_change_channel_plan(self, channel_plan):
        raise NotImplementedError()

    def rpc_wifi_register_multicast_address(self, mac):
        raise NotImplementedError()

    def rpc_wifi_unregister_multicast_address(self, mac):
        raise NotImplementedError()

    def rpc_wifi_rf_on(self):
        raise NotImplementedError()

    def rpc_wifi_rf_off(self):
        raise NotImplementedError()

    def rpc_wifi_on(self, mode):
        raise NotImplementedError()

    def rpc_wifi_off(self):
        raise NotImplementedError()

    def rpc_wifi_set_mode(self, mode):
        raise NotImplementedError()

    def rpc_wifi_off_fastly(self):
        raise NotImplementedError()

    def rpc_wifi_set_power_mode(self, ips_mode, lps_mode):
        raise NotImplementedError()

    def rpc_wifi_set_tdma_param(self, slot_period, rfon_period_len_1, rfon_period_len_2, rfon_period_len_3):
        raise NotImplementedError()

    def rpc_wifi_set_lps_dtim(self, dtim):
        raise NotImplementedError()

    def rpc_wifi_get_lps_dtim(self, dtim):
        raise NotImplementedError()

    def rpc_wifi_set_lps_thresh(self, mode):
        raise NotImplementedError()

    def rpc_wifi_set_lps_level(self, lps_level):
        raise NotImplementedError()

    def rpc_wifi_set_mfp_support(self, value):
        raise NotImplementedError()

    def rpc_wifi_start_ap(self, ssid, password, security_type, channel):
        raise NotImplementedError()

    def rpc_wifi_start_ap_with_hidden_ssid(self, ssid, password, security_type, channel):
        raise NotImplementedError()

    def rpc_wifi_set_pscan_chan(self, channel_list, pscan_config):
        raise NotImplementedError()

    def rpc_wifi_get_setting(self, ifname, pSetting):
        raise NotImplementedError()

    def rpc_wifi_set_network_mode(self, mode):
        raise NotImplementedError()

    def rpc_wifi_get_network_mode(self, pmode):
        raise NotImplementedError()

    def rpc_wifi_set_wps_phase(self, is_trigger_wps):
        raise NotImplementedError()

    def rpc_wifi_restart_ap(self, ssid, password, security_type, channel):
        raise NotImplementedError()

    def rpc_wifi_config_autoreconnect(self, mode, retry_times, timeout):
        raise NotImplementedError()

    def rpc_wifi_set_autoreconnect(self, mode):
        raise NotImplementedError()

    def rpc_wifi_get_autoreconnect(self, mode):
        raise NotImplementedError()

    def rpc_wifi_get_last_error(self):
        raise NotImplementedError()

    def rpc_wifi_add_custom_ie(self, cus_ie):
        raise NotImplementedError()

    def rpc_wifi_update_custom_ie(self, cus_ie, ie_index):
        raise NotImplementedError()

    def rpc_wifi_del_custom_ie(self):
        raise NotImplementedError()

    def rpc_wifi_set_indicate_mgnt(self, enable):
        raise NotImplementedError()

    def rpc_wifi_get_drv_ability(self, ability):
        raise NotImplementedError()

    def rpc_wifi_set_channel_plan(self, channel_plan):
        raise NotImplementedError()

    def rpc_wifi_get_channel_plan(self, channel_plan):
        raise NotImplementedError()

    def rpc_wifi_enable_forwarding(self):
        raise NotImplementedError()

    def rpc_wifi_disable_forwarding(self):
        raise NotImplementedError()

    def rpc_wifi_set_ch_deauth(self, enable):
        raise NotImplementedError()

    def rpc_wifi_get_band_type(self):
        raise NotImplementedError()

    def rpc_wifi_set_tx_pause_data(self, NewState):
        raise NotImplementedError()

    def rpc_wifi_get_reconnect_data(self, wifi_info):
        raise NotImplementedError()

    def rpc_wifi_clear_reconnect_data(self):
        raise NotImplementedError()

    def rpc_wifi_scan_start(self):
        raise NotImplementedError()

    def rpc_wifi_is_scaning(self):
        raise NotImplementedError()

    def rpc_wifi_scan_get_ap_records(self, number, _scanResult):
        raise NotImplementedError()

    def rpc_wifi_scan_get_ap_num(self):
        raise NotImplementedError()
