#
# Generated by erpcgen 1.10.0 on Sat Apr 22 14:59:30 2023.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for rpc_wifi_callback
class Irpc_wifi_callback(object):
    SERVICE_ID = 19
    RPC_WIFI_EVENT_CALLBACK_ID = 1
    RPC_WIFI_DNS_FOUND_ID = 2
    RPC_TCPIP_API_CALL_FN_ID = 3
    RPC_TCP_CONNECTED_FN_ID = 4
    RPC_TCP_RECV_FN_ID = 5
    RPC_TCP_ACCEPT_FN_ID = 6
    RPC_TCP_ERR_FN_ID = 7
    RPC_TCP_SENT_FN_ID = 8
    RPC_TCP_POLL_FN_ID = 9

    def rpc_wifi_event_callback(self, event):
        raise NotImplementedError()

    def rpc_wifi_dns_found(self, hostname, ipaddr, arg):
        raise NotImplementedError()

    def rpc_tcpip_api_call_fn(self, func, call):
        raise NotImplementedError()

    def rpc_tcp_connected_fn(self, func, arg, tpcb, err_val):
        raise NotImplementedError()

    def rpc_tcp_recv_fn(self, func, arg, tpcb, p_data, p_addr, err_val):
        raise NotImplementedError()

    def rpc_tcp_accept_fn(self, func, arg, newpcb, err_val):
        raise NotImplementedError()

    def rpc_tcp_err_fn(self, func, arg, err_val):
        raise NotImplementedError()

    def rpc_tcp_sent_fn(self, func, arg, tpcb, len):
        raise NotImplementedError()

    def rpc_tcp_poll_fn(self, func, arg, tpcb):
        raise NotImplementedError()


